// Nickname filter: one word list -> regexes for the app (index.html) and the
// Firestore rules (firestore.rules). Run after editing the lists:
//   node tools/nickfilter.mjs          (rewrites the generated blocks)
//   node tools/nickfilter.mjs --test   (runs the checks below)
import fs from 'fs';

// Roots, lowercase, no diacritics. Each letter automatically also matches its
// look-alikes (e->3, i->1/!/y, o->0, a->4/@, s->5/$ ...) and repeats (kuuurva).
// Plain regex syntax ( | ) ? is allowed; avoid [ ].
export const WORDS = [
  // Czech
  'kurv', 'kokot', 'curak', 'pic(a|o|u|e)', 'picus', 'zmrd', 'mrd', 'jeb', 'prdel', 'hovn',
  'srac(k|a)', 'chcan', 'kund(a|o|y|i)', 'hajzl', 'debil', 'kreten', 'dement', 'idiot', 'sukat',
  'buzn', 'buzer', 'negr', 'cigos', 'cikan', 'mamrd', 'kurev',
  // English
  'fu(c|k|q)k', 'phuc?k', 'fck', 'fcuk', 'fuk', 'shit', 'bitch', 'cunt', 'dick', 'cock', 'pussy', 'asshole',
  'bastard', 'whore', 'slut', 'faggot', 'nigg', 'niga', 'retard', 'wank', 'twat', 'tits', 'boob',
  'penis', 'vagin', 'dildo', 'porn', 'sex', 'piss',
  // Hate
  'hitler', 'nazi',
];
// Innocent words that contain a root; removed before checking.
export const ALLOW = ['picasso', 'epic', 'peacock', 'cockatoo', 'cockpit', 'cocktail', 'hitchcock', 'hancock',
  'scunthorpe', 'dickens', 'essex', 'sussex', 'sexta', 'shiitake', 'shitake'];

const LOOK = { a: 'a4@', b: 'b8', e: 'e3€', g: 'g9', i: 'i1!|y', l: 'l1|', o: 'o0', s: 's5$', t: 't7+', u: 'uv', y: 'yi1!|', z: 'z2' };
const cls = ch => { const set = LOOK[ch]; return set ? '[' + set.replace(/[\\\]^-]/g, '\\$&') + ']+' : ch + '+'; };
export const BAD = WORDS.map(w => w.replace(/[a-z]/g, cls)).join('|');
export const ALLOW_RE = ALLOW.join('|');
export const KEEP = 'a-z0-9@$!|€+';          // characters kept after normalization

export function normalize(name) {
  return name.toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '')
    .replace(new RegExp(`[^${KEEP}]`, 'g'), '').replace(new RegExp(ALLOW_RE, 'g'), '');
}
export const isBad = name => new RegExp(BAD).test(normalize(name));

function build() {
  const root = new URL('..', import.meta.url).pathname;
  const js = `// BEGIN NICKFILTER (generated by tools/nickfilter.mjs, do not edit by hand)
const NICK_BAD = new RegExp(${JSON.stringify(BAD)});
const NICK_ALLOW = new RegExp(${JSON.stringify(ALLOW_RE)}, 'g');
const NICK_STRIP = new RegExp(${JSON.stringify(`[^${KEEP}]`)}, 'g');
const badName = n => NICK_BAD.test(n.toLowerCase().normalize('NFD').replace(/[\\u0300-\\u036f]/g, '').replace(NICK_STRIP, '').replace(NICK_ALLOW, ''));
// END NICKFILTER`;
  const rq = s => "'" + s.replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'";
  const dia = [['[áàâä]', 'a'], ['č', 'c'], ['ď', 'd'], ['[éěë]', 'e'], ['[íï]', 'i'], ['ň', 'n'], ['[óöô]', 'o'],
    ['ř', 'r'], ['š', 's'], ['ť', 't'], ['[úůü]', 'u'], ['ý', 'y'], ['ž', 'z']];
  const rules = `    // BEGIN NICKFILTER (generated by tools/nickfilter.mjs, do not edit by hand)
    function normName(n) {
      return n.lower()${dia.map(([f, t]) => `.replace(${rq(f)}, ${rq(t)})`).join('')}
        .replace(${rq(`[^${KEEP}]`)}, '').replace(${rq(ALLOW_RE)}, '');
    }
    function isBadName(n) {
      return normName(n).matches(${rq('.*(' + BAD + ').*')});
    }
    // END NICKFILTER`;
  const put = (file, block) => {
    const p = root + file, s = fs.readFileSync(p, 'utf8');
    const re = /[ \t]*\/\/ BEGIN NICKFILTER[\s\S]*?\/\/ END NICKFILTER/;
    if (!re.test(s)) throw new Error('markers missing in ' + file);
    fs.writeFileSync(p, s.replace(re, () => block));
  };
  put('index.html', js);
  put('firestore.rules', rules);
  console.log('updated index.html and firestore.rules');
}

function test() {
  const bad = ['kurva', 'KURVA', 'k.u.r.v.a', 'kůrva', 'kuuurva', 'kurv4', 'k_u_r_v_a', 'Kokot', 'k0k0t', 'píča', 'P1ČA', 'pyča',
    'zmrd', 'Čurák', 'curak123', 'debil', 'd3b1l', 'prdel', 'pr-del', 'hovno', 'h0vn0', 'jebat', 'buzna',
    'fuck', 'FUCK', 'f*ck', 'fvck', 'fu©k', 'phuck?', 'fuuuck', 'sh1t', '$hit', 'b1tch', 'a$$hole', 'd1ck', 'c0ck', 'pu$$y',
    'n1gger', 'Hitler', 'nazi', 'xXkurvaXx', 'idiot', 'retard', 's3x', 'p0rn'];
  const good = ['Mia', 'Tomáš', 'Jakub', 'Nikola', 'Eliška', 'Anna', 'Kryštof', 'Vojtěch', 'Matěj', 'Adéla', 'Tereza',
    'Klára', 'Sofie', 'Viktorie', 'Dominik', 'Šimon', 'Lukáš', 'Filip', 'David', 'Ondřej', 'Kateřina', 'Barbora',
    'Natálie', 'Michaela', 'Petr', 'Martin', 'Hana', 'Lucie', 'Sára', 'Ema', 'Julie', 'Nicolas', 'Pikachu',
    'Picasso', 'EpicAnimal', 'Peacock', 'Kakadu', 'Plejtvák', 'Kajman', 'Sup', 'Kos', 'Sýkorka', 'Class', 'Bass',
    'Fagot', 'Sexta B', 'Suková', 'Kuřátko', 'Liška', 'Ježek', 'Delfín', 'Tygřík', 'Kočička', 'Pepa', 'Hitchcock',
    'Dickens', 'Scunthorpe', 'Assassin', 'Glass', 'Kristýna', 'Kuba', 'Honza', 'Radek', 'Jirka', 'Vašek', 'Tadeáš'];
  const known = new Set();
  const missed = bad.filter(n => !isBad(n) && !known.has(n));
  const falsePos = good.filter(isBad);
  console.log('missed:', missed, '| false positives:', falsePos, '| known misses still missed:', [...known].filter(n => !isBad(n)));
  if (missed.length || falsePos.length) process.exit(1);
}

process.argv.includes('--test') ? test() : build();
